---
- name: Install & prepare Attack Range prerequisites (exact steps you provided)
  hosts: all
  become: yes

  tasks:
    - name: Apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      apt:
        name:
          - python3
          - git
          - unzip
          - python3-pip
          - curl
        state: present

    - name: Download Terraform zip
      get_url:
        url: "{{ terraform_url }}"
        dest: "{{ terraform_zip }}"
        mode: '0644'

    - name: Unarchive Terraform
      unarchive:
        src: "{{ terraform_zip }}"
        dest: /tmp
        remote_src: yes

    - name: Move terraform binary to /usr/local/bin
      command: mv /tmp/terraform /usr/local/bin/terraform
      args:
        creates: /usr/local/bin/terraform

    - name: Ensure terraform is executable
      file:
        path: /usr/local/bin/terraform
        mode: '0755'
        owner: root
        group: root

    - name: Clone the Attack Range repository
      git:
        repo: "https://github.com/splunk/attack_range.git"
        dest: /home/ubuntu/attack_range
        version: HEAD
        update: no

    - name: Ensure attack_range repo is owned by ubuntu
      file:
        path: /home/ubuntu/attack_range
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu

    - name: Download AWS CLI v2 zip
      get_url:
        url: "{{ awscli_url }}"
        dest: "{{ awscliv2_zip }}"
        mode: '0644'

    - name: Unarchive AWS CLI v2
      unarchive:
        src: "{{ awscliv2_zip }}"
        dest: /tmp
        remote_src: yes
        creates: /tmp/aws/install

    - name: Install AWS CLI v2
      command: /tmp/aws/install --update
      args:
        creates: /usr/local/bin/aws

    - name: Verify aws --version
      command: aws --version
      register: aws_version
      ignore_errors: yes

    - name: Print aws version (for debug)
      debug:
        msg: "{{ aws_version.stdout | default(aws_version.stderr) }}"

    - name: Ensure .aws directory exists in remote user's HOME
      file:
        path: "{{ ansible_env.HOME }}/.aws"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user_id | default(ansible_user) }}"
        group: "{{ ansible_user_id | default(ansible_user) }}"

    - name: Create AWS credentials file
      copy:
        dest: "{{ ansible_env.HOME }}/.aws/credentials"
        content: |
          [default]
          aws_access_key_id = {{ aws_access_key }}
          aws_secret_access_key = {{ aws_secret_key }}
        owner: "{{ ansible_user_id | default(ansible_user) }}"
        group: "{{ ansible_user_id | default(ansible_user) }}"
        mode: '0600'

    - name: Create AWS config file (region)
      copy:
        dest: "{{ ansible_env.HOME }}/.aws/config"
        content: |
          [default]
          region = {{ aws_region }}
        owner: "{{ ansible_user_id | default(ansible_user) }}"
        group: "{{ ansible_user_id | default(ansible_user) }}"
        mode: '0644'
  
    - name: Install Poetry and Python dependencies
      # run this as ubuntu so poetry installs into /home/ubuntu/.local
      become: false
      shell: |
        curl -sSL https://install.python-poetry.org/ | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        $HOME/.local/bin/poetry self add poetry-plugin-shell
        $HOME/.local/bin/poetry install --no-interaction
      args:
        chdir: /home/ubuntu/attack_range
        executable: /bin/bash

    - name: Ensure existing attack_range.yml is removed so configure won't prompt
      # run as ubuntu to manage the file under /home/ubuntu
      become: false
      file:
        path: /home/ubuntu/attack_range/attack_range.yml
        state: absent

    - name: Run attack_range configure with scripted answers (expect)
      # run as ubuntu so poetry and venv match user
      become: false
      vars:
        project_dir: /home/ubuntu/attack_range
        poetry_path: /home/ubuntu/.local/bin/poetry
      expect:
        command: "{{ poetry_path }} run python attack_range.py configure"
        chdir: "{{ project_dir }}"
        timeout: 1200
        responses:
          # answer overwrite prompt first (robust regex to tolerate ANSI/control chars)
          '.*File .*attack_range\\.yml.*are you sure you want to continue.*': "Y\n"

          # remaining scripted prompts -> responses (each response ends with \n)
          'Select cloud provider': "aws\n"
          'Enter a master password for your attack_range': "Admin123\n"
          'Detected existing key .* would you like to use it': "Yes\n"
          'Included ssh private key:': "/home/ubuntu/attack_range/ubuntu-67460.key\n"
          'Enter region to build in': "ap-southeast-2\n"
          'Enter public ips that are allowed to reach the attack_range': "0.0.0.0/0\n"
          'Enter attack_range name': "ar_Attack\n"
          'Shall we build a windows server': "Yes\n"
          'Which version should it be': "2022\n"
          'Should the windows server be a domain controller': "Yes\n"
          'Should we install red team tools on the windows server': "Yes\n"
          'Should we install badblood on the windows server, which will populate the domain with objects': "Yes\n"
          'Shall we build a linux server': "Yes\n"
          'Shall we build a kali linux machine': "Yes\n"
          'Shall we build nginx plus web proxy': "Yes\n"
          'Shall we build zeek server': "Yes\n"
          'Shall we build snort server': "Yes\n"
          'Shall we include Splunk SOAR': "No\n"
