---
- name: Setup Splunk Attack Range (fully automated, venv-based, v4.x)
  hosts: attack_range
  become: yes
  gather_facts: false

  vars:
    terraform_version: "1.9.8"
    terraform_zip: "/home/ubuntu/terraform.zip"
    awscli_zip: "/home/ubuntu/awscliv2.zip"
    venv_path: "/home/ubuntu/attack_range/venv"
    repo_dir: "/home/ubuntu/attack_range"

    attack_range_provider: "{{ lookup('env','ATTACK_RANGE_PROVIDER') | default('aws') }}"
    attack_range_region: "{{ lookup('env','ATTACK_RANGE_REGION') | default('ap-southeast-2') }}"
    attack_range_password: "{{ lookup('env','ATTACK_RANGE_PASSWORD') | default('changeme') }}"
    attack_range_instance_type: "{{ lookup('env','ATTACK_RANGE_INSTANCE_TYPE') | default('t2.medium') }}"
    attack_range_key_name: "{{ lookup('env','ATTACK_RANGE_KEY_NAME') | default('attack-range-key-pair') }}"
    attack_range_private_key: "{{ lookup('env','ATTACK_RANGE_PRIVATE_KEY') | default('/home/ubuntu/.ssh/Admin123.pem') }}"

  pre_tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Test SSH connectivity
      ansible.builtin.ping:

  tasks:
    - name: Update apt cache and upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - python3-full
          - git
          - unzip
          - curl
          - zip
          - build-essential
          - libffi-dev
          - libssl-dev
          - python3-dev
          - dos2unix
        state: present
        update_cache: yes

    - name: Download Terraform
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "{{ terraform_zip }}"
        mode: '0644'

    - name: Unarchive Terraform
      ansible.builtin.unarchive:
        src: "{{ terraform_zip }}"
        dest: "/usr/local/bin/"
        remote_src: yes
      args:
        creates: "/usr/local/bin/terraform"

    - name: Ensure terraform is in PATH
      ansible.builtin.lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export PATH="/usr/local/bin:$PATH"'
        create: yes
      become_user: ubuntu

    - name: Clone attack_range repo (v4.0.0)
      ansible.builtin.git:
        repo: "https://github.com/splunk/attack_range.git"
        dest: "{{ repo_dir }}"
        version: "v4.0.0"
        force: yes
      become_user: ubuntu

    - name: Verify terraform binary is available
      ansible.builtin.command: terraform version
      register: terraform_version_check
      changed_when: false

    - name: Show terraform version
      ansible.builtin.debug:
        msg: "{{ terraform_version_check.stdout }}"

    - name: Download AWS CLI v2
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ awscli_zip }}"
        mode: '0644'

    - name: Unzip AWS CLI
      ansible.builtin.unarchive:
        src: "{{ awscli_zip }}"
        dest: /home/ubuntu/
        remote_src: yes

    - name: Install AWS CLI
      ansible.builtin.command:
        cmd: ./aws/install --update
        chdir: /home/ubuntu
        creates: /usr/local/bin/aws

    - name: Patch requirements.txt for Python 3.12 compatibility
      ansible.builtin.replace:
        path: "{{ repo_dir }}/requirements.txt"
        regexp: 'cffi==1.13.2'
        replace: 'cffi==1.15.1'
      ignore_errors: yes

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv "{{ venv_path }}"
      args:
        creates: "{{ venv_path }}"
      become_user: ubuntu

    - name: Upgrade pip/setuptools/wheel
      ansible.builtin.shell: |
        set -e
        source "{{ venv_path }}/bin/activate"
        pip install --upgrade pip setuptools wheel
      args:
        executable: /bin/bash
      become_user: ubuntu

    - name: Install python dependencies in venv
      ansible.builtin.shell: |
        set -e
        source "{{ venv_path }}/bin/activate"
        cd "{{ repo_dir }}"
        pip install -r requirements.txt
        pip install "python-terraform==0.10.1" "python-hcl2==4.3.3"
        pip install --upgrade "tabulate>=0.9.0" "wrapt>=1.15.0"
        pip install --upgrade "six"
        pip install --force-reinstall --no-cache-dir "urllib3<2" boto3 botocore
        pip install "setuptools<68.0.0" "packaging<21.0"
      args:
        executable: /bin/bash
      become_user: ubuntu

    - name: Copy attack_range config from default YAML
      ansible.builtin.copy:
        src: "{{ repo_dir }}/configs/attack_range_default.yml"
        dest: "{{ repo_dir }}/attack_range.yml"
        remote_src: yes
        force: no

    - name: Terraform init
      ansible.builtin.command:
        cmd: /usr/local/bin/terraform init -input=false
        chdir: "{{ repo_dir }}/terraform/aws"
      register: terraform_init
      changed_when: "'Terraform has been successfully initialized' in terraform_init.stdout"
      failed_when: terraform_init.rc not in [0, 1]

    - name: Run attack_range build (YAML config)
      ansible.builtin.shell: |
        set -e
        source "{{ venv_path }}/bin/activate"
        python attack_range.py -c attack_range.yml build
      args:
        chdir: "{{ repo_dir }}"
        executable: /bin/bash
      become_user: ubuntu
      register: attack_range_build
      retries: 3
      delay: 10
      until: attack_range_build.rc == 0
      failed_when: attack_range_build.rc != 0

    - name: Show build logs if failed
      ansible.builtin.debug:
        msg: |
          rc={{ attack_range_build.rc }}
          stdout={{ attack_range_build.stdout | default('') }}
          stderr={{ attack_range_build.stderr | default('') }}
      when: attack_range_build.rc != 0
