---
- name: Setup Splunk Attack Range
  hosts: attack_range
  become: yes

  pre_tasks:
    - name: Ensure SSH key permissions are correct
      ansible.builtin.file:
        path: "/mnt/c/Users/Dhaarun M V/OneDrive/Documents/Downloads/Attack_range.pem"
        mode: '0600'
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install base tools
      ansible.builtin.apt:
        name:
          - python3.10
          - git
          - unzip
          - python3-pip
          - curl
        state: present

    - name: Install Terraform
      ansible.builtin.shell: |
        curl -s https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
        unzip -o terraform.zip
        sudo mv terraform /usr/local/bin/
      args:
        chdir: /home/ubuntu
        creates: /usr/local/bin/terraform

    - name: Clone attack range repo
      ansible.builtin.git:
        repo: https://github.com/splunk/attack_range.git
        dest: /home/ubuntu/attack_range
        version: master

    - name: Install AWS CLI
      ansible.builtin.shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install --update
      args:
        chdir: /home/ubuntu
        creates: /usr/local/bin/aws

    - name: Install Poetry
      ansible.builtin.shell: |
        curl -sSL https://install.python-poetry.org/ | python3 -
        echo 'export PATH="/home/ubuntu/.local/bin:$PATH"' >> /home/ubuntu/.bashrc
      args:
        executable: /bin/bash
        creates: /home/ubuntu/.local/bin/poetry

    - name: Install Poetry plugin and dependencies
      ansible.builtin.shell: |
        /home/ubuntu/.local/bin/poetry self add poetry-plugin-shell
        cd /home/ubuntu/attack_range && /home/ubuntu/.local/bin/poetry install
      args:
        executable: /bin/bash

    - name: Run attack_range configure (manual step)
      ansible.builtin.shell: |
        cd /home/ubuntu/attack_range
        /home/ubuntu/.local/bin/poetry run python attack_range.py configure
      args:
        executable: /bin/bash
      async: 0
      poll: 0   # run interactively; requires user input
